Update keto dependencies versions
atls/nestjs pull request #280
Opened 2023-09-13 19:47 UTC by IgorSmugalov

All dependencies updated to the last versions in the keto module
Except:
- typescript

2023-09-13 21:36 UTC, TorinAsakura commented
конфликт

2023-09-14 12:21 UTC, SlumberyDude approved these changes

2023-09-14 18:55 UTC, SlumberyDude commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
Что за `ts-morph`? Дополнительная зависимость появилась при обновлении?

2023-09-14 19:09 UTC, IgorSmugalov commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
Да, без нее не проходили тайпчеки, в предыдущих PR подняли версию TS, сейчас проверю, возможно все будет работать без этого пакета

2023-09-14 19:17 UTC, SlumberyDude commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
@IgorSmugalov Если от него зависит какой-то из пакетов, то можно его пропатчить в yarnrc, возможно это будет лучше. Но тут я не уверен, какой вариант правильнее

2023-09-14 19:19 UTC, IgorSmugalov commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
ошибся по тайпчекам, без `ts-morph` нее не проходит `yarn build`:

```shell
➤ YN0000: ┌ Library Build
➤ YN0000: │ .yarn/__virtual__/@nestjs-graphql-virtual-ed9b9dd9bf/3/.yarn/berry/cache/@nestjs-graphql-npm-12.0.9-c02a849a7f-9.zip/node_modules/@nestjs/graphql/dist/graphql-ast.explorer.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find module 'ts-morph' or its corresponding type declarations.
➤ YN0000: │ 
➤ YN0000: │ 
```

2023-09-14 19:28 UTC, SlumberyDude commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
@IgorSmugalov Понял, ну в принципе думаю можно зависимость добавить, патч смотрится менее выигрышно как по мне

2023-09-14 19:32 UTC, IgorSmugalov commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
@SlumberyDude , 2й день работаю с yarn, быстрый поиск не дал ответа по `пропатчить в yarnrc`, прошу ссылку или подсказку по теме

2023-09-14 19:44 UTC, SlumberyDude commented on packages/keto/package.json
> +    "ts-morph": "19.0.0"
@IgorSmugalov Вот тут можешь глянуть https://yarnpkg.com/configuration/yarnrc . Нас интересуют `packageExtensions`. Они позволяют добавить пакету зависимость в дерево, иногда ошибки решаются только таким способом. Но он весьма груб и действует на весь репозиторий.

Тут у нас не ошибка тайпчека, а ошибка билда. Думаю в таком случа лучше все же зависимость иметь явно внутри модуля.

2023-09-15 00:25 UTC, TorinAsakura requested changes
https://github.com/atls/nestjs/pull/281#pullrequestreview-1627878581

2023-09-15 15:27 UTC, IgorSmugalov commented
@SlumberyDude сделал ребейз, не могу понять почему у меня продублировали коммиты, плюс при разрешении конфликтов с файлами pnp.cjc и yarn.lock выбирал вариант 'использовать свою версию' и почему-то в таком случае всегда натыкался на проблемы с тестами

2023-09-15 15:46 UTC, IgorSmugalov commented
@SlumberyDude я как раз зафорсил через --amend pnp.cjc и yarn.lock чтобы прошли чеки
еще бы разобраться с 2мя соседними моими PR, в какой момент я накосячил - понимаю, сделал ревёрт мерджа, но далее не хочу двигаться, так как не думаю, что смогу сам правильно разобраться

2023-09-18 11:21 UTC, ArtemMakhaydinov commented
@TorinAsakura, @SlumberyDude
Все успешно обновилось за исключением:
"@nestjs/core": "10.1.3" 
При повышении чек выдает:
<details>
```➤ YN0000: │ packages/keto/src/guards/keto-access-control.guard.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Object is of type 'unknown'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ packages/keto/src/guards/keto-access-control.guard.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Object is of type 'unknown'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ packages/keto/src/guards/keto-access-control.guard.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Object is of type 'unknown'.```<details/>

Так же был был дополнительно установлен пакет ts-morph, его требовал при обновлении @nestjs/graphql.

2023-09-18 11:24 UTC, SlumberyDude commented
@ArtemMakhaydinov Покажи это место в коде на которое он ругается, может можно там типчик поправить?

2023-09-18 11:26 UTC, ArtemMakhaydinov commented
@SlumberyDude 
@nestjs/graphql без ts-morph или @nestjs/core 10.2+ версии?

2023-09-18 11:27 UTC, SlumberyDude commented
@ArtemMakhaydinov Если ts-morph нужен то можно его поставить в dev. Я про nestjs/core, что там за тип валится?

2023-09-18 11:33 UTC, ArtemMakhaydinov commented
@SlumberyDude 
Если апнуть @nestjs/core, ide при билде выдает это и  подчеркивает константу ```policy``` в указанном файле.
<details>
➤ YN0000: ┌ Library Build  <br />
➤ YN0000: │ packages/keto/src/guards/keto-access-control.guard.ts  <br />
➤ YN0000: │   <br />
➤ YN0000: │   Error: Object is of type 'unknown'.  <br />
➤ YN0000: │   <br />
➤ YN0000: │   <br />
➤ YN0000: │ packages/keto/src/guards/keto-access-control.guard.ts  <br />
➤ YN0000: │   <br />
➤ YN0000: │   Error: Object is of type 'unknown'.  <br />
➤ YN0000: │   <br />
➤ YN0000: │   <br />
➤ YN0000: │ packages/keto/src/guards/keto-access-control.guard.ts  <br />
➤ YN0000: │   <br />
➤ YN0000: │   Error: Object is of type 'unknown'.
<details/>

2023-09-18 11:38 UTC, SlumberyDude commented
@ArtemMakhaydinov там у `policy` поменялся тип на unknown? Можешь предложить исправление?

2023-09-18 12:26 UTC, ArtemMakhaydinov commented
@SlumberyDude при объявлении ```policy``` в вызове метода поставлен тайп <any>, я не силен в TS, но мне казалось, что при вызовах функций/методов, тайп не нужно указывать. Без этого <any> все нормально билдится, чекается и тестится на последней версии @nestjs/core. Вот эта строка(в изначальном виде):
<details>
const policy = this.reflector.get<any>(ACCESS_POLICY_METADATA, context.getHandler())
<details/>

2023-09-18 12:31 UTC, SlumberyDude commented
@ArtemMakhaydinov Вроде приемлемо. Ты кстати тег `details` закрываешь неправильно, ставь слеш перед `details`, а то у тебя иногда вложенные списки получаются)

2023-09-18 23:21 UTC, TorinAsakura commented
> #281 (review)

проблема не решена

2023-09-19 06:13 UTC, SlumberyDude commented
> проблема не решена

Какая? Вроде там все версии обновлены

2023-09-19 06:15 UTC, SlumberyDude requested changes

2023-09-19 06:15 UTC, SlumberyDude commented on packages/keto/package.json
> +    "typescript": "*"
Сделай фиксированную версию тайпскрипта, мажорную четверку, можешь как в корневом пакете.

2023-09-19 06:36 UTC, ArtemMakhaydinov commented
> проблема не решена

В более поздних версиях ```@oryd/keto-client``` и ```@ory/keto-client``` API поменялся

2023-09-19 07:41 UTC, ArtemMakhaydinov commented
> > #281 (review)
> 
> проблема не решена

@TorinAsakura В более поздних версиях ```@oryd/keto-client``` и ```@ory/keto-client``` API поменялся

2023-09-19 07:44 UTC, SlumberyDude approved these changes

2023-09-19 08:43 UTC, TorinAsakura commented
@ArtemMakhaydinov Ну так и чего? А обновление зависимостей, по-твоему, это просто изменение версий в пекедже?

2023-09-19 08:45 UTC, ArtemMakhaydinov commented
> @ArtemMakhaydinov Ну так и чего? А обновление зависимостей, по-твоему, это просто изменение версий в пекедже?

Женя сказал в код не лезть - я не лез. Теперь полез разбираться.

2023-09-19 08:46 UTC, ArtemMakhaydinov commented
@TorinAsakura Женя сказал в код не лезть. Полез разбираться.

2023-09-19 12:02 UTC, ArtemMakhaydinov commented
@TorinAsakura установил ```@ory/keto-client: 0.0.0-alpha.58``` вместо ```@oryd/keto-client: 0.0.0-alpha.46```. В ```ory``` используется ```axios``` вместо ```request```, у него схема респонса выглядит вот так:
```js
{
  data: {},
  status: 200,
  statusText: 'OK',
  headers: {},
  config: {},
  request: {}
}
```
Поменял ```body``` на ```data``` - собирается, чекается, тестится. Для подъема на следующую версию 0.6 и выше полагаю надо переписать ```keto-access-control.guard.ts``` переписывать, т.к. модуля ```EnginesApi``` в новых версиях уже нет. Пока не понимаю как, но могу покопаться.

2023-09-19 12:12 UTC, SlumberyDude requested changes

2023-09-19 12:12 UTC, SlumberyDude commented on packages/keto/package.json
> +    "@ory/keto-client": "0.0.0-alpha.58"
Это последняя `0.0.0` версия, но не последняя в принципе. Думаю надо попробовать поднять до `0.11.0-alpha.0`

2023-09-19 12:20 UTC, ArtemMakhaydinov commented on packages/keto/package.json
> +    "@ory/keto-client": "0.0.0-alpha.58"
@SlumberyDude выше не работает, я написал в предыдущем коменте, там API поменялось. Сижу разбираюсь.

2023-09-19 12:42 UTC, SlumberyDude commented on packages/keto/package.json
> +    "@ory/keto-client": "0.0.0-alpha.58"
@ArtemMakhaydinov Окей, тогда попробуй разобраться, что там можно сделать

2023-09-19 14:12 UTC, ArtemMakhaydinov commented on packages/keto/package.json
> +    "@ory/keto-client": "0.0.0-alpha.58"
@SlumberyDude я не знаю как исправить. Вообще другая структура приложения, модули, использующие keto нужно переписывать, а это пока не в моей компетенции. Я только могу оставить как есть на ```"@ory/keto-client": "0.0.0-alpha.58"```

2023-09-19 14:34 UTC, SlumberyDude commented on packages/keto/package.json
> +    "@ory/keto-client": "0.0.0-alpha.58"
@TorinAsakura Нужно переписывать модули, использующие keto, или остановиться на `"@ory/keto-client": "0.0.0-alpha.58"`?

2023-09-19 16:59 UTC, TorinAsakura commented
@ArtemMakhaydinov То есть не понимаешь как? Не понимаешь как код писать или что?

2023-09-19 17:31 UTC, ArtemMakhaydinov commented
@TorinAsakura я не понимаю что именно должно получиться на выходе. Этот модуль куда-то встраивается и предоставляет там какие-то сервисы. Для этого создается объект из класса на 1К строк, предоставляемого апишкой старой версии keto. Что именно из этого ожидается потребителем сервиса я не знаю, в новых версиях keto структура API другая, а у ```@atls/nestjs-keto``` отсутствует документация.

2023-09-19 23:51 UTC, TorinAsakura commented
> @TorinAsakura я не понимаю что именно должно получиться на выходе. Этот модуль куда-то встраивается и предоставляет там какие-то сервисы. Для этого создается объект из класса на 1К строк, предоставляемого апишкой старой версии keto. Что именно из этого ожидается потребителем сервиса я не знаю, в новых версиях keto структура API другая, а у `@atls/nestjs-keto` отсутствует документация.

Оставь эту задачу. Рановато тебе пока туда нырять.

2023-09-20 06:08 UTC, SlumberyDude approved these changes

2023-09-20 07:52 UTC, ArtemMakhaydinov commented
@TorinAsakura в виде компромисса ты мог бы объяснить что требуется, а я попытаюсь реализовать. Мне пока в любом случае есть чем заняться.

2023-09-20 20:26 UTC, TorinAsakura commented
> @TorinAsakura в виде компромисса ты мог бы объяснить что требуется, а я попытаюсь реализовать. Мне пока в любом случае есть чем заняться.

Тебе надо взять наш модуль для нестжс
Поднять дефолтный инстанс кето и протестировать его работу
Так понятней?

2023-09-21 08:02 UTC, ArtemMakhaydinov commented
@TorinAsakura все понятно, кроме тестирования. Я использовал Jest, но год назад и не на модулях NestJS. Есть примеры использования?

2023-09-21 09:09 UTC, TorinAsakura commented
@ArtemMakhaydinov Тебе дока неста не помогла или что? Интеграционные тесты есть в других пакетах

2024-01-10 07:11 UTC, Nelfimov requested changes
доработать API

2024-01-19 14:29 UTC, TorinAsakura approved these changes

2024-01-19 14:29 UTC, merged