Update kratos dependencies versions
atls/nestjs pull request #281
Opened 2023-09-14 12:15 UTC by IgorSmugalov

**All dependencies updated to the last versions in the `kratos` module**

**Except:**

`@ory/kratos-client` - moved from the alpha version to the release, needs to update all api in the `kratos` module

`get-port` - updated to 6.1.2, the maximum available version: 7.0.0, an error occurs when trying to update to 7.0.0

<details><summary>Error log</summary>
  
```shell
➤ YN0000: │ ../../.yarn/berry/cache/get-port-npm-7.0.0-72b8a92f99-9.zip/node_modules/get-port/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Module '"node:net"' has no exported member 'type'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/get-port-npm-7.0.0-72b8a92f99-9.zip/node_modules/get-port/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: ',' expected.
```
</details>

`@types/express` - updated to 4.17.13, the maximum available version: 4.17: when trying to use it, there is a conflict with `@types/express-serve-static-core`, failed to raise the version above 4.17.13, [issue about this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53397)

2023-09-14 13:18 UTC, SlumberyDude approved these changes

2023-09-14 17:25 UTC, IgorSmugalov commented
bumped get-potr and typescript as https://github.com/atls/nestjs/pull/275/commits/c1f749f45364339f3ef1e15de5e3b80b0e170a24

2023-09-14 17:26 UTC, TorinAsakura commented
конфликт

2023-09-14 22:56 UTC, TorinAsakura requested changes
у тебя keto deprecated…

2023-09-14 22:56 UTC, TorinAsakura commented on packages/keto/package.json
> +    "@oryd/keto-client": "0.0.0-alpha.46"
https://www.npmjs.com/package/@oryd/keto-client

2023-09-15 00:25 UTC, TorinAsakura commented on packages/keto/package.json
> +    "@oryd/keto-client": "0.0.0-alpha.46"
погоди, почему у тебя в Пре кратоса обновление кето?

2023-09-15 06:05 UTC, IgorSmugalov commented on packages/keto/package.json
> +    "@oryd/keto-client": "0.0.0-alpha.46"
Решил попробовать сделать все действия через интерфейс Webstorm, (до этого всегда работал с командной строкой либо SourceTree), в итоге смержил все неправильно и понял проблему только после пуша, для исправления планирую сделать `git revert -m 1 <hash ошибочного коммита слияния>` с этой веткой и веткой обновления logger

2023-09-18 08:38 UTC, SlumberyDude requested changes
Затронуты лишние модули, если бы можно было как-то целиком выпилить коммиты, которые их вызвали

2023-09-18 11:55 UTC, ArtemMakhaydinov commented
Все зависимости успешно обновлены до последних версий кроме:
```"@ory/kratos-client": "0.5.5-alpha.4"``` - в следующей же минорной версии изменен API, выдает кучу ошибок по несуществующим импортам
```"@types/express": "4.17.14"``` - при попытке обновиться выше чек выдает:
<details>
➤ YN0000: ┌ Typecheck  <br />
➤ YN0000: │ ../../../.yarn/berry/cache/@types-express-npm-4.17.17-46fe8173db-9.zip/node_modules/@types/express/index.d.ts  <br />
➤ YN0000: │   <br />
➤ YN0000: │   Erro: Conflicting definitions for 'express-serve-static-core' found at '/home/artem/.yarn/berry/cache/@types-express-serve-static-core-npm-4.17.36-87a82f5a6b-9.zip/node_modules/@types/express-serve-static-core/index.d.ts' and   <br />
➤ YN0000: │       '/home/artem/.yarn/berry/cache/@types-express-serve-static-core-npm-4.17.24-cd6b9fd3ba-  <br />9.zip/node_modules/@types/express-serve-static-core/index.d.ts'. Consider installing a specific version of this library to resolve the 
➤ YN0000: │       conflict.  <br />
➤ YN0000: │         The file is in the program because:  <br />
➤ YN0000: │           Type library referenced via 'express-serve-static-core' from file '/home/artem/.yarn/berry/cache/@types-express-npm-4.17.13-0e12fe9c24-9.zip/node_modules/@types/express/index.d.ts' with packageId   <br />
➤ YN0000: │       '@types/express-serve-static-core/index.d.ts@4.17.24'  <br />
➤ YN0000: │           Imported via 'express-serve-static-core' from file '/home/artem/.yarn/berry/cache/@types-express-npm-4.17.13-0e12fe9c24-9.zip/node_modules/@types/express/index.d.ts' with packageId   <br />
➤ YN0000: │       '@types/express-serve-static-core/index.d.ts@4.17.24'  <br />
➤ YN0000: │           Type library referenced via 'express-serve-static-core' from file '/home/artem/.yarn/berry/cache/@types-express-npm-4.17.17-46fe8173db-9.zip/node_modules/@types/express/index.d.ts' with packageId   <br />
➤ YN0000: │       '@types/express-serve-static-core/index.d.ts@4.17.36'
<details/>

2023-09-19 06:09 UTC, SlumberyDude approved these changes

2023-09-20 00:06 UTC, TorinAsakura commented
конфликт

2023-09-20 09:58 UTC, SlumberyDude approved these changes

2023-09-20 20:30 UTC, TorinAsakura commented
> Все зависимости успешно обновлены до последних версий кроме: `"@ory/kratos-client": "0.5.5-alpha.4"` - в следующей же минорной версии изменен API, выдает кучу ошибок по несуществующим импортам `"@types/express": "4.17.14"` - при попытке обновиться выше чек выдает:
> 
> ➤ YN0000: ┌ Typecheck 
> ➤ YN0000: │ ../../../.yarn/berry/cache/@types-express-npm-4.17.17-46fe8173db-9.zip/node_modules/@types/express/index.d.ts 
> ➤ YN0000: │ 
> ➤ YN0000: │ Erro: Conflicting definitions for 'express-serve-static-core' found at '/home/artem/.yarn/berry/cache/@types-express-serve-static-core-npm-4.17.36-87a82f5a6b-9.zip/node_modules/@types/express-serve-static-core/index.d.ts' and 
> ➤ YN0000: │ '/home/artem/.yarn/berry/cache/@types-express-serve-static-core-npm-4.17.24-cd6b9fd3ba- 
> 9.zip/node_modules/@types/express-serve-static-core/index.d.ts'. Consider installing a specific version of this library to resolve the ➤ YN0000: │ conflict. 
> ➤ YN0000: │ The file is in the program because: 
> ➤ YN0000: │ Type library referenced via 'express-serve-static-core' from file '/home/artem/.yarn/berry/cache/@types-express-npm-4.17.13-0e12fe9c24-9.zip/node_modules/@types/express/index.d.ts' with packageId 
> ➤ YN0000: │ '@types/express-serve-static-core/index.d.ts@4.17.24' 
> ➤ YN0000: │ Imported via 'express-serve-static-core' from file '/home/artem/.yarn/berry/cache/@types-express-npm-4.17.13-0e12fe9c24-9.zip/node_modules/@types/express/index.d.ts' with packageId 
> ➤ YN0000: │ '@types/express-serve-static-core/index.d.ts@4.17.24' 
> ➤ YN0000: │ Type library referenced via 'express-serve-static-core' from file '/home/artem/.yarn/berry/cache/@types-express-npm-4.17.17-46fe8173db-9.zip/node_modules/@types/express/index.d.ts' with packageId 
> ➤ YN0000: │ '@types/express-serve-static-core/index.d.ts@4.17.36'

ну так погоди, с проблемами нужно разбираться. Какой смысл в проверке твоих навыков, если при возникновении ошибок ты просто фиксируешься на первой безопасной версии? Копай.

2024-08-27 17:06 UTC, closed without merging