Update logger dependencies versions
atls/nestjs pull request #282
Opened 2023-09-14 12:36 UTC by IgorSmugalov

All dependencies updated to the last versions in the `logger` module

Skipped:
`typeorm` - by definition of issue

2023-09-14 19:30 UTC, SlumberyDude requested changes
Сюда как-то 3 пакета сразу залетели - `logger`, `keto` и `kratos`. Надо бы только логгер оставить в этом ПР

2023-09-14 19:54 UTC, IgorSmugalov commented
@SlumberyDude Понял причину ошибки: поспешил с merge, в итоге сюда, как и в соседний PR попало лишнее, буду исправлять

2023-09-15 13:11 UTC, SlumberyDude commented
@IgorSmugalov Запрашивай повторные PR после фиксов

2023-09-18 07:52 UTC, ArtemMakhaydinov commented
@IgorSmugalov либо я чет не так делаю, либо с бренчой что-то не так, но у меня даже yarn install не проходит с такой ошибкой:
```➤ YN0046: A variant of the conflicting lockfile failed to parse```

Я могу просто заново все сделать и зафорсить? То же касается kratos и keto. Это будет явно быстрей, чем чужие коммиты и мерджи разгребать.

2023-09-18 10:39 UTC, TorinAsakura commented
@ArtemMakhaydinov Делай.

2023-09-18 11:39 UTC, ArtemMakhaydinov commented
Все зависимости успешно обновлены до последних версий.

2023-09-18 22:35 UTC, TorinAsakura commented
> Все зависимости успешно обновлены до последних версий.

нужно перезапрашивать ревью

2023-09-19 06:12 UTC, SlumberyDude requested changes

2023-09-19 06:12 UTC, SlumberyDude commented on packages/logger/package.json
>      "typeorm": "*"
Поставь typeorm последнюю минорную двойку, как в других пакетах стоит +-

2023-09-19 08:06 UTC, SlumberyDude approved these changes

2023-09-20 00:03 UTC, TorinAsakura approved these changes

2023-09-20 00:03 UTC, merged