Update dependencies
atls/nestjs pull request #283
Opened 2023-09-14 22:02 UTC by RimidalU

Updated to the latest dependencies in the typeorm-seeding.
Exception:

- typesense to 0.15.0 (latest 1.7.1)

- decamelize 5.0.0 (latest 6.0.0)

2023-09-15 11:09 UTC, SlumberyDude requested changes

2023-09-15 11:09 UTC, SlumberyDude commented on packages/typesense/package.json
> +    "@atls/logger": "^0.0.2",
нефиксированные версии

2023-09-15 17:13 UTC, RimidalU commented on packages/typesense/package.json
> +    "@atls/logger": "^0.0.2",
Сорян, прозевал как-то ((

2023-09-15 17:48 UTC, SlumberyDude approved these changes

2023-09-16 17:15 UTC, TorinAsakura requested changes
Конфликты

2023-09-17 17:45 UTC, RimidalU commented
@TorinAsakura 
Видно я не осознал всю глубину глубин rebase(((

Исходные данные:
 - репозиторий с мастера которого я сделал свою ветку, чего-то там наговнокодил и это даже прошло неподкупеый апрув.
 - но пока я этим занимался кто-то в ветку мастер залили что-то новое (вроде и не пересекались но .pnp.cjs и yarn.lock обновились(мне кажется постоянный кейс))
 
 сейчас мне нужно:
 1  из ветки master сделать git pull
 2 из моей рабочей ветки сделать git rebase master
 3 фикшу конфликты:
   - условно оставляю если одинаковое то с master, (т.к. скорее всего они бы и остались если бы я реально создавал ветку уже после чужого коммита)
   -если новое - то своё
 - git rebase --contine
 - повторить по колличеству конфликтных коммитов
 4 коммичу полученные измененмя (хотя, возможно здесь косяк и изменений быть не должно?)
 5 git pull моя_ветка --rebase
 6 фикшу конфликты - на этот раз осталяю только изменения из моей локальной ветки + git rebase --contine
 7 git push origin моя_ветка.
 
 Но когда я это делаю то появляются косяки:
  - появляются новые задублированные коммиты;
  - конфлик файлов (.pnp.cjs и yarn.lock) остался
  
  Почему они возникают и как решить?
  И еще: я не заметил что бы проверка запускалась поле моих действий. Это значит 
  -что конфликтыне файлы не изменились ;
  -что мои действия не вызвали перезапуск тестов;
  -или я просто три раза не заметил этот перезапуск?

2023-09-17 20:45 UTC, TorinAsakura commented
@RimidalU Так, ну давай разбираться:

1. Дублированные коммиты: Если ты делаешь git pull с --rebase после ребейза - ясен красен произойдёт дублирование, так как происходит применение твоих коммитов поверх текущего состояния удаленной ветки в итоге получается наслаивание…

2. Конфликты в `.pnp.cjs` и `yarn.lock`: Это лучше просто перезаписывать своими

3. Тесты не запускаются: о каких конкретно тестах идёт речь? 

### Чо делаем

1. Сделай git pull origin master находясь в master.
2. Переключись на свою ветку и сделай git rebase master.
3. Разреши конфликты и сделай git add . и git rebase --continue.
4. После успешного ребейза сделай git push origin имя_твоей_ветки --force-with-lease.

Про --force-with-lease я уже писал ранее - он тупо безопаснее, чем просто --force, потому что  не перезапишет изменения, сделанные другими людьми

### Про форс-пуши

Форс-пуш — это хреновая практика, но она приемлема в ветках, которые не являются общими (`master`, stage,`development`). Если ты единственный, кто работает в этой ветке, и ты точно знаешь, что делаешь, форс-пуш допустим, но, я бы рекомендовал вообще использовать его как последнюю меру…

2023-09-18 21:24 UTC, RimidalU commented
@TorinAsakura , я всё-таки его осилил)))

2023-09-19 06:11 UTC, SlumberyDude approved these changes

2023-09-20 00:10 UTC, TorinAsakura approved these changes

2023-09-20 00:10 UTC, merged