feat: bump gateway dependencies versions
atls/nestjs pull request #287
Opened 2023-09-15 14:15 UTC by ArtemMakhaydinov

2023-09-15 14:31 UTC, SlumberyDude commented
@ArtemMakhaydinov Что за файл? Кстати, не закрывай PR. Не надо для каждого коммита создавать новый PR, просто делай коммит и пуш в удаленную ветку, она сама подтянется в PR. В первый раз мы удаляли PR потому что там ветка была из форка.

2023-09-15 14:32 UTC, SlumberyDude approved these changes

2023-09-15 14:33 UTC, ArtemMakhaydinov commented
@SlumberyDude текстовый файл, собирал туда все, думал в комменты пихнуть под спойлер, но не влезает.

2023-09-16 17:12 UTC, TorinAsakura requested changes
Конфликты

2024-07-02 15:18 UTC, closed without merging