Feat/package batch queue
atls/nestjs pull request #324
Opened 2024-10-08 10:23 UTC by OsirisAnubiz

2024-10-08 11:09 UTC, Nelfimov requested changes
проверь чеки

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/module/batch-queue.module.ts
> +    const memoryCheckerOptionsProvider = {
вынеси создание провайдеров в файл рядом `...providers.ts`

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/checkers/memory-checker/memory-checker.ts
> +  static jobName = 'memory-checker-job'
если константа - то СНЕЙК_КЕЙС

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/checkers/memory-checker/memory-checker.ts
> +    @BatchChecker() private checker: Checker,
`readonly`

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/checkers/memory-checker/memory-checker.ts
> +export class MemoryChecker implements OnModuleInit {
мне кажется мы дублируем функционал `terminus`. Оно нам здесь нужно? Ведь можно на уровне приложения/сервиса добавить проверку памяти, а для наших тестов добавить terminus в тестовое приложение

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/utils/index.ts
> +export * from './mutex.js'
можно вынести на верхний уровень

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/errors/index.ts
> +export * from './base-queue.error.js'
можно вынести в корень модуля

2024-10-08 11:09 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/utils/index.ts
> +export * from './mutex.js'
точнее в корень

2024-10-08 11:18 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/integration/test/batch-queue.test.ts
> +    await new Promise((res) => {
@Nelfimov 
Чеки буду исправлять.
Тут такой механизм необходим, т.к. обработка очереди случается при её переполнении или, когда случается timeout существования батча.  В тестах я проверяю, что по таймауту случиться обработка.

2024-10-08 11:20 UTC, Nelfimov commented on packages/nestjs-batch-queue/integration/test/batch-queue.test.ts
> +    await new Promise((res) => {
может тогда паблить эвент - завершение обработки?

2024-10-08 11:20 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/src/module/batch-queue.constants.ts
> +export const BATCH_QUEUE_MODULE_OPTIONS = Symbol('BATCH_QUEUE_MODULE_OPTIONS')
@Nelfimov для каждой константы должен быть отдельный файл?

2024-10-08 11:22 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/integration/test/batch-queue.test.ts
> +    await new Promise((res) => {
Попробую сделать так

2024-10-08 11:48 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/module/batch-queue.constants.ts
> +export const BATCH_QUEUE_MODULE_OPTIONS = Symbol('BATCH_QUEUE_MODULE_OPTIONS')
нет. Просто `/constants/batch-queue.constants.ts`

2024-10-08 15:34 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/src/checkers/memory-checker/memory-checker.ts
> +export class MemoryChecker implements OnModuleInit {
Удалил MemoryChecker

2024-10-08 15:49 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/integration/test/batch-queue.test.ts
> +    await new Promise((res) => {
Переписал на ожидание пока не придёт определённое количество успешных добавлений, но setTimeout остался до сих пор. Не понимаю как от него избавиться

2024-10-08 15:55 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/utils/index.ts
> +export * from './mutex.js'
тут не так много кода чтобы тянуть лишнюю зависимость. Если тебе действительно нужна библиотека за доп функционалом - тяни

2024-10-08 15:56 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/errors/index.ts
> +export * from './base-queue.error.js'
так проще ориентироваться - твоя вложенность папок не дает преимуществ. А так в библиотеке будет все на виду. Тем более объекты ошибок

2024-10-08 15:56 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/src/batch-queue/utils/index.ts
> +export * from './mutex.js'
Не нужна, тогда вынесу

2024-10-08 15:56 UTC, Nelfimov commented on packages/nestjs-batch-queue/integration/test/batch-queue.test.ts
> +    await new Promise((res) => {
первое что приходит на ум: https://testing-library.com

`waitFor` с таймаутом

2024-10-08 15:57 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/src/batch-queue/errors/index.ts
> +export * from './base-queue.error.js'
Понял, спасибо

2024-10-08 17:27 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/errors/index.ts
> +export * from './base-queue.error.js'
Можно отключить тапочек. Поищи в наших проектах typecheckSkipLibCheck

2024-10-09 08:53 UTC, Nelfimov requested changes

2024-10-09 08:53 UTC, Nelfimov commented on packages/nestjs-batch-queue/package.json
> +    "@jest/globals": "29.7.0",
в `dev` зафиксируй версии

2024-10-09 08:53 UTC, Nelfimov commented on packages/nestjs-batch-queue/integration/test/batch-queue.test.ts
> +  const waitForConsumeCount = async (expectedCount: number, timeout = 5000): Promise<void> => {
вынеси рядом в хелперы

2024-10-09 08:53 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/module/constants/index.ts
> +export * from './batch-queue.constants.js'
корень - это прямо в `/src`

2024-10-09 08:53 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/module/constants/index.ts
> +export * from './batch-queue.constants.js'
т.е. будет так - `/src/constants/index.ts`

2024-10-09 08:53 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.errors.ts
> +export class CheckFailedError extends BaseQueueError {
тоже вынеси в корень - `/src/errors/...`

2024-10-09 08:53 UTC, Nelfimov commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.interface.ts
> +export type QueueName = string
разнеси по файлам - что требует `batch-queue`, что `checker` и т.д.

2024-10-09 10:59 UTC, Nelfimov approved these changes

2024-10-09 11:03 UTC, OsirisAnubiz commented
@Nelfimov нужно, чтобы Андрей тоже заапрувил или можно мёржить?

2024-10-09 11:04 UTC, Nelfimov commented
> @Nelfimov нужно, чтобы Андрей тоже заапрувил или можно мёржить?

Конечно чтобы Андрей посмотрел

2024-10-09 22:25 UTC, TorinAsakura requested changes
- В случае сложных состояний или дополнительных логик проверки стоит подумать о более гибкой архитектуре, возможно, через отдельные сервисы или стратегии для выполнения проверок.
- Если в будущем эта штука будет расширяться например, добавление других типов обработчиков или сложных условий, возможно, имеет смысл вынести логику в отдельные классы или стратегии, чтобы поддерживать SRP (Single Responsibility Principle)
- не увидел ни одного JSDoc

А вообще - очень хорошая работа, я давно не видел, чтобы человек с первого месяца так хорошо вкатывался. Молодцы.

2024-10-09 22:25 UTC, TorinAsakura commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.ts
> +    unlock()
Ты отлично обрабатываешь исключения с помощью try-catch, но стоит убедиться, что всегда происходит unlock(), даже если произошла ошибка. Сейчас разблокировка происходит только в случае ошибки. Можно использовать finally, чтобы гарантировать освобождение мьютекса

2024-10-09 22:25 UTC, TorinAsakura commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.ts
> +  private startTimerIfNecessary(queueName: QueueName): void {
Сначала ты сбрасываешь существующий таймер и затем устанавливаешь новый, однако, если очередь будет очень активно использоваться, таймеры могут постоянно перезапускаться. Возможно, имеет смысл сначала проверить, есть ли текущий таймер, и только если его нет, запускать новый

2024-10-09 22:25 UTC, TorinAsakura commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.ts
> +  private checkAllChecks(): void {
кажется тут можно юзать class-validator

2024-10-10 09:02 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.ts
> +  private startTimerIfNecessary(queueName: QueueName): void {
Это действительно правильное поведение, я пропустил момент

2024-10-10 09:11 UTC, OsirisAnubiz commented on packages/nestjs-batch-queue/src/batch-queue/batch-queue.ts
> +  private checkAllChecks(): void {
@TorinAsakura
Не понял зачем использовать `class-validator`.

Этот метод проверяет есть ли провеки с плохим статусом (`false`) и если нашлись проверки с таким статусом, то бросается ошибка.

Возможно имелисось ввиду то, что я не понял. Если так прошу пояснить.

2024-10-10 21:46 UTC, TorinAsakura approved these changes
Для первой либы - хорошая работа

2024-10-11 07:56 UTC, Nelfimov approved these changes

2024-10-11 07:56 UTC, merged