Feat/nestjs connectrpc
atls/nestjs pull request #328
Opened 2024-10-30 18:17 UTC by TorinAsakura

#327

2024-10-30 18:51 UTC, OsirisAnubiz commented
@TorinAsakura можно чеки прям в твоей ветке поправить?

2024-10-31 20:02 UTC, OsirisAnubiz commented on packages/nestjs-connectrpc/package.json
> +  "version": "0.0.0",
Думаю нормально, не меняю

2024-10-31 20:05 UTC, OsirisAnubiz commented on packages/nestjs-connectrpc/package.json
> +    "@nestjs/platform-express": "^10.2.4",
Остальные пакеты на `express`, не актуально думаю

2024-10-31 20:09 UTC, Nelfimov requested changes

2024-10-31 20:09 UTC, Nelfimov commented on packages/nestjs-connectrpc/package.json
> +    "@nestjs/platform-express": "^10.2.4",
так что мешает перевести все на `fastify` постепенно?

2024-10-31 20:56 UTC, OsirisAnubiz commented on packages/nestjs-connectrpc/src/connectrpc.server.ts
> +  startServer(resolve: () => void, reject: (error: Error) => void): void {
> в твоем предложении нет await, поэтому не понятно зачем делать асинхронным

Без `async` линтер ругается

2024-10-31 20:59 UTC, OsirisAnubiz commented on packages/nestjs-connectrpc/package.json
> +    "@nestjs/platform-express": "^10.2.4",
> так что мешает перевести все на fastify постепенно?

Андрей пока сказал не переводить ([сообщение](https://t.me/c/1057842456/42128/73140))

2024-10-31 21:02 UTC, OsirisAnubiz commented on packages/nestjs-connectrpc/src/connectrpc.server.ts
> +  async close(callback?: () => void): Promise<void> {
> не понял что имеешь в виду

```ts
await HTTPServer.start(() => {
  // some logic...
 })
```

```ts
await HTTPServer.start()
// some logic...
```

Вроде одно и то же но при этом без лишнего параметра в виде колбека

2024-10-31 21:04 UTC, OsirisAnubiz commented on packages/nestjs-connectrpc/src/connectrpc.strategy.ts
> +      this.messageHandlers.set(route, modifiedCallback)
```ts
    const route = isString(pattern) ? pattern : JSON.stringify(pattern)
    if (isEventHandler) {
      const modifiedCallback = callback
      modifiedCallback.isEventHandler = true
      this.messageHandlers.set(route, modifiedCallback)
      return // добавил тут return, чтобы не добавлять в messageHandlers дважды
    }
    this.messageHandlers.set(route, callback)
```

2024-11-01 15:01 UTC, OsirisAnubiz approved these changes

2024-11-01 17:27 UTC, Nelfimov requested changes

2024-11-01 17:27 UTC, Nelfimov commented on packages/nestjs-connectrpc/package.json
> +    "@bufbuild/protobuf": "^1.10.0",
зафиксируй зависимости

2024-11-01 17:28 UTC, Nelfimov commented on packages/nestjs-connectrpc/src/connectrpc.server.ts
> +  startServer(resolve: () => void, reject: (error: Error) => void): void {
а на что ругается? Делать async ради линтера но при этом это не пользоваться `await` - такое себе

2024-11-05 08:53 UTC, Nelfimov approved these changes

2024-11-05 08:53 UTC, merged